"""Download tokenizer files for the S2 parity spike.

Fetches only the small tokenizer artifacts (tokenizer.json, tokenizer_config.json,
special_tokens_map.json, config.json) for each candidate tokenizer, never model
weights. Files land in ../models/<local_name>/ (gitignored; regenerate with this
script). Revisions are pinned to a specific commit SHA per repo so a rerun months
later downloads the same bytes.

ckiplab/bert-tiny-chinese-ner ships no tokenizer.json (slow-tokenizer-only repo).
This script verifies its vocab.txt is byte-identical to bert-base-chinese's, then
reuses bert-base-chinese's tokenizer.json for that row instead of guessing at a
third-party mirror. The verification and the substitution are both recorded in
the manifest so the decision is auditable, not silent.

Usage:
    uv run --python 3.11 --with-requirements requirements.txt python scripts/download_models.py
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path

from huggingface_hub import hf_hub_download
from huggingface_hub.utils import EntryNotFoundError

SPIKE_ROOT = Path(__file__).resolve().parent.parent
MODELS_DIR = SPIKE_ROOT / "models"

# Written inside the gitignored models/ dir (not results/): this is raw
# provenance for the download step, regenerated by this script and folded
# into the committed results/s2_results.json by compare_and_report.py.
MANIFEST_PATH = MODELS_DIR / "download_manifest.json"

TOKENIZER_FILES = [
    "tokenizer.json",
    "tokenizer_config.json",
    "special_tokens_map.json",
    "config.json",
    # Not needed for tokenization itself (tokenizer.json is self-contained),
    # but downloaded when present so vocab-identity claims (e.g. ckiplab vs.
    # bert-base-chinese) can be verified against the actual file bytes
    # rather than asserted from memory.
    "vocab.txt",
]


@dataclass
class TokenizerSpec:
    """One tokenizer under test."""

    name: str
    hf_repo_id: str
    revision: str
    reuse_tokenizer_json_from: str | None = None
    note: str = ""
    downloaded_files: list[str] = field(default_factory=list)


SPECS: list[TokenizerSpec] = [
    TokenizerSpec(
        name="bert-base-chinese",
        hf_repo_id="bert-base-chinese",
        revision="8f23c25b06e129b6c986331a13d8d025a92cf0ea",
        note="WordPiece, ~21k zh-focused vocab. Resolves to google-bert/bert-base-chinese.",
    ),
    TokenizerSpec(
        name="ckiplab-bert-tiny-chinese-ner",
        hf_repo_id="ckiplab/bert-tiny-chinese-ner",
        revision="a18df36c7f73ae3329877506be48a86c09599e8d",
        reuse_tokenizer_json_from="bert-base-chinese",
        note=(
            "Academia Sinica CKIP NER fine-tune. Ships tokenizer_config.json / "
            "special_tokens_map.json / vocab.txt but no tokenizer.json (slow "
            "tokenizer only). Its tokenizer_config.json has name_or_path="
            "'bert-base-chinese'. This script verifies vocab.txt is byte-identical "
            "to bert-base-chinese's before reusing that tokenizer.json here."
        ),
    ),
    TokenizerSpec(
        name="bert-base-multilingual-cased",
        hf_repo_id="bert-base-multilingual-cased",
        revision="3f076fdb1ab68d5b2880cb87a0886f315b8146f8",
        note="mBERT WordPiece, ~119k vocab across 104 languages.",
    ),
    TokenizerSpec(
        name="distilbert-base-multilingual-cased",
        hf_repo_id="distilbert-base-multilingual-cased",
        revision="45c032ab32cc946ad88a166f7cb282f58c753c2e",
        note="Distilled mBERT, shares mBERT's WordPiece vocab.",
    ),
    TokenizerSpec(
        name="xlm-roberta-base",
        hf_repo_id="xlm-roberta-base",
        revision="e73636d4f797dec63c3081bb6ed5c7b0bb3f2089",
        note="SentencePiece unigram, ~250k vocab.",
    ),
]


def sha256_of(path: Path) -> str:
    """Return the hex SHA256 digest of a file's bytes."""
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def download_spec(spec: TokenizerSpec) -> dict:
    """Download a tokenizer's small artifact files and return its manifest entry."""
    local_dir = MODELS_DIR / spec.name
    local_dir.mkdir(parents=True, exist_ok=True)

    for filename in TOKENIZER_FILES:
        if filename == "tokenizer.json" and spec.reuse_tokenizer_json_from:
            continue
        try:
            hf_hub_download(
                repo_id=spec.hf_repo_id,
                filename=filename,
                revision=spec.revision,
                local_dir=str(local_dir),
            )
            spec.downloaded_files.append(filename)
        except EntryNotFoundError:
            continue

    vocab_sha256 = None
    if (local_dir / "vocab.txt").exists():
        vocab_sha256 = sha256_of(local_dir / "vocab.txt")

    entry: dict = {
        "hf_repo_id": spec.hf_repo_id,
        "hf_revision": spec.revision,
        "note": spec.note,
        "downloaded_files": sorted(spec.downloaded_files),
        "vocab_txt_sha256": vocab_sha256,
    }

    if spec.reuse_tokenizer_json_from:
        source_dir = MODELS_DIR / spec.reuse_tokenizer_json_from
        source_vocab = source_dir / "vocab.txt"
        this_vocab = local_dir / "vocab.txt"
        if not (source_vocab.exists() and this_vocab.exists()):
            raise RuntimeError(
                f"cannot verify vocab parity for {spec.name}: vocab.txt missing "
                f"on one side (source={source_vocab.exists()}, this={this_vocab.exists()})"
            )
        source_sha = sha256_of(source_vocab)
        this_sha = sha256_of(this_vocab)
        vocab_identical = source_sha == this_sha
        entry["vocab_identical_to_source"] = vocab_identical
        if not vocab_identical:
            raise RuntimeError(
                f"{spec.name}: vocab.txt does NOT match {spec.reuse_tokenizer_json_from} "
                f"({this_sha} != {source_sha}); refusing to silently reuse a mismatched "
                "tokenizer.json. Investigate before rerunning."
            )
        (local_dir / "tokenizer.json").write_bytes((source_dir / "tokenizer.json").read_bytes())
        entry["tokenizer_json_source"] = (
            f"reused from {spec.reuse_tokenizer_json_from} "
            f"(vocab.txt verified byte-identical, sha256={this_sha})"
        )

    tokenizer_json_path = local_dir / "tokenizer.json"
    if not tokenizer_json_path.exists():
        raise RuntimeError(f"{spec.name}: no tokenizer.json present after download")
    entry["tokenizer_json_sha256"] = sha256_of(tokenizer_json_path)
    entry["tokenizer_json_size_bytes"] = tokenizer_json_path.stat().st_size

    return entry


def main() -> None:
    MODELS_DIR.mkdir(parents=True, exist_ok=True)

    manifest: dict[str, dict] = {}
    # bert-base-chinese first: ckiplab's entry reuses its tokenizer.json.
    ordered = sorted(SPECS, key=lambda s: s.reuse_tokenizer_json_from is not None)
    for spec in ordered:
        print(f"downloading {spec.name} ({spec.hf_repo_id}@{spec.revision[:8]})...")
        manifest[spec.name] = download_spec(spec)
        print(f"  tokenizer.json sha256={manifest[spec.name]['tokenizer_json_sha256']}")

    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")
    print(f"\nwrote {MANIFEST_PATH}")


if __name__ == "__main__":
    main()
